### ISSUE TITLE
bug: CI tests are not working due to incompatible python and mamba version

### ISSUE THREAD

**Issue by fgypas** [zavolanlab/zarp#110]
**Describe the bug**

In the CI we specify Python 3.7.4 and mamba 0.16. See here: https://github.com/zavolanlab/zarp/blob/dev/.github/workflows/ci.yml#L27-L28

As mentioned in #108 for unknown reasons it defaults to Python 3.10. But Python 3.10 is incompatible with mamba 0.16 so the tests CI fails at the beginning.

**Expected behavior**
It should work for all python versions.

**Additional context**
One solution would be to not specify exact mamba version. So switch to `mamba-version: "*"` from `mamba-version: "0.16.0"`.

Also this link has some related info: https://github.com/conda-incubator/setup-miniconda/issues/274

**Comment by uniqueg** [comment]
I think not pinning a version for Mamba is a very good idea! But we should still upgrade Python as described in #109.
