### ISSUE TITLE
Add optional installation of ZARP-cli

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/zarp#114]
**Is your feature request related to a problem? Please describe.**
It's tricky to install ZARP from ZARP-cli (see zavolanlab/zarp-cli/issues/22), but the other way around is easy once ZARP-cli is on Bioconda (zavolanlab/zarp-cli/issues/37).

**Describe the solution you'd like**
Provide an `enviroinment.cli.yml` file in `install/` that people can optionally use to update the minimum ZARP installation with ZARP-cli, just like we do for Singularity with `environment.root.yml`. Describe in the documentation.

**Additional context**
Blocked until zavolanlab/zarp-cli/issues/37 is implemented.

**Comment by mkatsanto** [comment]
Hi @uniqueg shouldn't we also add a test in the ci on this? Do you think we should trigger the workflow with the small samples or have a zarp --help test?

**Comment by mkatsanto** [comment]
This issue relies on #108, as the versions of python and biopython create errors when updating with the zarp-cli. 
Some suggestions for compatible versions with the zarp-cli are:
python=3.10.1
snakemake=7.19
bedtools=2.30
biopython=1.81

**Comment by uniqueg** [comment]
I would not pin precise versions of the dependencies but rather open-ended ranges, and only for those dependencies where we really need a minimal version. I think @fgypas did that for ZARP-cli on Bioconda as well, and I'm planning to do that on the `requirements.txt` and in HTSinfer as well. I guess from your side, you could make sure that you do that for ZARP as well.

As for the installation instructions. I'll take care of that once we have all of these in place.

**Comment by mkatsanto** [comment]
Thanks @uniqueg and regarding the testing for the zarp-cli? should I add a minimal ci test checking the installation or a more elaborate integration workflow trigger or nothing at this point?

**Comment by uniqueg** [comment]
You can open another issue for that, but I don't think it's urgent.
