### ISSUE TITLE
SRA download workflow does not support DRR, ERR identifiers

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/zarp#130]
The following [statement](https://github.com/zavolanlab/zarp/blob/72b735480de64aa4c1e769fd3fce73f81dab0643/workflow/rules/sra_download.smk#L133-L136) in the current SRA download workflow descriptor file prevents DRR and ERR identifiers from being supported:

```python
        expand(
            os.path.join(DOWNLOAD_DIR, "{sample}", "{sample}.processed"),
            sample=samples[samples.index.str.contains("SRR")].index.tolist(),
        ),
```

**Comment by dominikburri** [comment]
some context: only NCBI's SRA database supported now. Need to extend to EBI's and DDBJ database.
From https://www.ncbi.nlm.nih.gov/sra/docs/srasearch/: 
S – NCBI’s SRA database
E – EBI’s database
D – DDBJ database
