### ISSUE TITLE
docs: update links/info referring to old repository

### ISSUE THREAD

**Issue by dominikburri** [zavolanlab/zarp#2]
Currently there are still some links from gitlab, e.g. on how to clone the repository. 
This should be replaced by the new links.

**Comment by XFarooqi** [comment]
## Need Help

I am sorry but I am unable to understand the requirement clearly. Can you please tell me in detail that:
1. Where to Find new Links (e.g. The directory or the file name)
2. And Where To Place the new links

**Comment by dominikburri** [comment]
I'm sorry it was a bit unspecific. I mean not only links within the repository but also URLs that point to the previous gitlab instance.
E.g. in `README.md` you find the following code:
`git clone ssh://git@git.scicore.unibas.ch:2222/zavolan_group/pipelines/zarp.git`

which should be replaced by the new URL on this github page. 

Other links and URLs might still exist and one needs to search for them and subsequently replace them.
