### ISSUE TITLE
chore: inspect the required resource scaling 

### ISSUE THREAD

**Issue by AngryMaciek** [zavolanlab/zarp#20]
**Is your feature request related to a problem? Please describe.**
We have encountered a problem with `cutadapt` crashing due to low memory on some datasets; we should check how all the steps scale with the input data size and account for that accordingly in the pipeline.

**Comment by mkatsanto** [comment]
Suggested solution: 

- According to snakemake, the resources can be specified for each rule. The idea is to have some scaling factor there to more accurately estimate  the required resources. (source: https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#resources)
Snakemake resources should have priority over any other defaults.
- Verify that the resources overrides any cluster.json specifications
- Verify that the profiles implemented in zarp do not affect or override these options. 
To efficiently estimate that, need some real samples of different sizes to estimate the scaling factors.

**Comment by dominikburri** [comment]
I just saw that what I described is raised in issue #19. Sorry for mix-ups! 

I guess here the idea is to have scaling factors based on known samples?

**Comment by mkatsanto** [comment]
Actually, these two issues are intertwined. In this issue we want to improve our first guess of resources and make it scale with the size of the file. 
In #19 we want to enable the attempts, so rerunning the workflow and how to increase these resources.

**Comment by dominikburri** [comment]
see comment in issue #19: https://github.com/zavolanlab/zarp/issues/19#issuecomment-1066717776
