### ISSUE TITLE
feat: samtools update in singularity containers

### ISSUE THREAD

**Issue by AngryMaciek** [zavolanlab/zarp#22]
We have just updated `samtools` to version to `1.9` from bioconda, the previous one raised errors, see [here](https://github.com/merenlab/anvio/issues/1479).
We should do the same for singularity runs too, to use the same versions of tools consistently.

**Comment by AngryMaciek** [comment]
I do not remember how the containers are generated now, possibly @fgypas could help?

**Comment by fgypas** [comment]
For bioconda they automatically build them for us after every upload. You can find the ones for samtools here: https://quay.io/repository/biocontainers/samtools?tab=tags

**Comment by noepozzan** [comment]
Hi @mkatsanto @dominikburri or whoever knows about this issue..
So, I am just supposed to build an image with samtools=1.9?
What is with this image here: https://github.com/zavolanlab/Dockerfiles/blob/master/samtools/1.10/Dockerfile ?
Should I be using quay.io for this?
Thank you

**Comment by mkatsanto** [comment]
Hi @noepozzan , there are singularity images in the biocontainers mentioned above. We no longer make our own singularity images but rely mainly on the bioconda existing containers. If we do not find that then we would have to build it and add it. I think they have samtools 1.9 there: https://quay.io/repository/biocontainers/samtools?tab=tags . Take a look and try to replace the path in the singularity option for the rule and test if it works.

**Comment by noepozzan** [comment]
hi @mkatsanto, thank you, that makes sense.
