### ISSUE TITLE
Fastqc report after adapter trimming

### ISSUE THREAD

**Issue by mkatsanto** [zavolanlab/zarp#30]
**Is your feature request related to a problem? Please describe.**
The current fastqc is applied to the raw fastq files. However it is still relevant for the user to see what the quality of reads is or if there are still overrepresented sequences after the trimming. 

**Describe the solution you'd like**
Introduce a second rule fastqc_trimmed, where the trimmed fastq file is used as input.

**Comment by dominikburri** [comment]
As a sidenote, fastqc currently uses 2 threads. However, this is only used when multiple samples are run at once, which seems not to be the case based on the wildcards. 
So maybe best to remove that in order to preserve resources.

**Comment by dominikburri** [comment]
See commit 8718100aeef874e5196ad83daf226fe2c7fa7b35 in branch `manage-resources`.

Please note that this commit does not totally fix the issue. I think the main problem in my solution is that I renamed files and replaced `.` with `_`. This triggers fastqc to see too many files.
