### ISSUE TITLE
bug: local test with conda fails?

### ISSUE THREAD

**Issue by ninsch3000** [zavolanlab/zarp#52]
**Describe the bug**
Running `bash tests/test_integration_workflow_with_conda/test.local.sh` exits with 
```
WorkflowError:
Python package jinja2 must be installed to create reports.
  File "/home/christina/miniconda3/envs/zarp/lib/python3.7/site-packages/snakemake/report/__init__.py", line 594, in auto_report
```
This happens at the step 
```
+ snakemake --snakefile=../../workflow/Snakefile --configfile=../input_files/config.yaml --report=snakemake_report.html
```
although the environment.yml for zarp conda env specifies ` jinja2=2.11.2`

**To Reproduce**
1. Follow installation instructions in zarp `README` to create the conda env (I did a fresh creation of the conda env root & update with dev)
2. `conda activate zarp`
3. run `bash tests/test_integration_workflow_with_conda/test.local.sh`

**Expected behavior**
exit status 0. 

**Screenshots**

**Additional context**

**Comment by AngryMaciek** [comment]
This is very bizarre since "The steps to reproduce" are executed within the CI (job: `integration-conda`) and it passes there, right?

**Comment by fgypas** [comment]
Whats OS do you use?

**Comment by AngryMaciek** [comment]
More strange update:  
Now the CI in #53 fails for the same reason. However CI in #50 did not threw that error...  
Hmm...

**Comment by fgypas** [comment]
I will have a look at the conda tests.

**Comment by ninsch3000** [comment]
https://github.com/zavolanlab/zarp/issues/52#issuecomment-1068305184
Ubuntu 20.04.04

**Comment by AngryMaciek** [comment]
Since this issue is directly interfering with my CI tests on #53 I have already fixed it there.  
I just updated `jinja2` version in our _main_ and _root_ conda env. recipes :)  
The PR is still WIP but will mark it ready soon.

**Comment by fgypas** [comment]
Thanks. I was also able to reproduce the issue. Indeed the jinja2 version update will fix this.
