### ISSUE TITLE
refactor: remove {seqmode} wildcard if applicable

### ISSUE THREAD

**Issue by ninsch3000** [zavolanlab/zarp#60]
**Is your feature request related to a problem? Please describe.**
As sample names have to be unique, there could not be one sample with two different sequencing modes. That means the seqmode doesn't have to appear in filenames, and consequently the wildcard {seqmode} is redundant. However, whether this is true has to be checked first.

**Describe the solution you'd like**
Check whether it might be possible to remove seqmode from filenames. If yes, implement.

**Describe alternatives you've considered**
Maybe this theory is wrong and we need seqmode as a wildcard.

**Additional context**
At least in some places it should be possible to remove the wildcard

**Comment by fgypas** [comment]
This is fine. We don't need to spend more time on it.
I am closing this.
