### ISSUE TITLE
Download genome resources

### ISSUE THREAD

**Issue by mzavolan** [zavolanlab/zarp#66]
The genome sequence and annotation file for the species from which the RNA-seq data comes are needed as inputs to zarp. 

We use the reference files from ENSEMBL. 

The user supplies the species name (e.g. homo_sapiens) or taxon ID (e.g. 9606) and the chromosome sequences that compose the karyotype (no haplotypes) are downloaded, along with the corresponding annotation.

**Comment by mkatsanto** [comment]
This will be implemented in the zarp-cli https://github.com/zavolanlab/zarp-cli/issues/8
