### ISSUE TITLE
Github actions too slow

### ISSUE THREAD

**Issue by mkatsanto** [zavolanlab/zarp#71]
**Is your feature request related to a problem? Please describe.**
Github actions ci test creates  multiple times the same environment and creates different jobs for tasks that can be in one job.
Mamba implementation may make it faster.

**Describe the solution you'd like**
Mamba implementation and all tasks in one job, while creating the zarp env once

**Additional context**
https://github.com/conda-incubator/setup-miniconda

**Comment by AngryMaciek** [comment]
`mamba` implementation is OK, although I think its still experimental in that action.

I think squashing them all into one CI job is not a good idea. Having separate tests in separate jobs allows for them to run in parallel. So you loose some time by re-createing the envs but you gain some some by running workflows next to each other. And that way we have it now the design is cleaner.

**Comment by uniqueg** [comment]
Did you look at caching environments? https://github.com/marketplace/actions/setup-miniconda#caching-environments
