### ISSUE TITLE
Du not require logo & URL for MultiQC report

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/zarp#72]
The user should have the ability to choose not to supply a custom logo and URL for the MultiQC report when running ZARP. The outcome should be that no logo and URL are provided in the report.

To achieve this, the user should be able to specify empty strings for these parameters. To further improve user experience, the `report_logo` and `report_url` parameters could/should be made entirely optional in `config.yaml` (then taking on empty strings as defaults).

Another question in this context is whether, in the current implementation, a user is allowed to specify an HTTP(S) URL pointing to a logo, rather than the logo itself. It would just be nice to test this out while implementing the above, so that we can document that behavior more accurately.

**Comment by AngryMaciek** [comment]
I have tested out a few cases of MultiQC report generation based on various **MultiQC configs**:

- local logo + specified URL -> Proper report logo with a link (default)
- local logo + no URL field -> Proper logo with no link
- no logo field + specified URL -> nothing in the report
- no logo field + no URL field -> nothing in the report
- logo empty string + URL specified -> broken image in the report + link works
- local logo + URL empty string ->  logo OK, link to the report itself
- logo empty string + URL empty string -> broken image + link to the report itself
- https string (png) as logo image + specified URL -> nothing in the report

This is MultiQC's default behaviour, I will just adjust our custom script for its configfile generation to link various user's input possibilities to some reasonable outcomes from the above.

So: No, URLs pointing to a logo don't work.

**Comment by uniqueg** [comment]
Thanks a lot @AngryMaciek, good to know the default behavior and that URLs are not supported for the logo.
