### ISSUE TITLE
rule star_rpm with FileNotFoundError

### ISSUE THREAD

**Issue by dominikburri** [zavolanlab/zarp#79]
This is more of a note, if others experience similar behaviour, so that they can rule out that this is the problem. 

**Describe the bug**
Workflow fails on rule `star_rpm` with FileNotFoundError. 

**To Reproduce**
1. create a zarp run, but keep config and results directories separate. 
2. Start zarp with Singularity from base repo directory.
3. Workflow will likely fail on `star_rpm`
4. Remove `shadow: "full"` from the rule, restart.
5. Workflow will run through.

**Expected behavior**
The [shadow keyword](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#shadow-rules) takes relative paths to the working directory. Maybe a more meaningful error message would help, or a check for the file locations could be done prior to the start. 

**Additional context**
The *shadow* keyword reduces the disk space footprint on the workflow and makes it possible to delete whole temp directories. 
But it requires that all the files are sub directories of the working directory. 
Maybe removing this altogether is less hassle?

**Comment by mkatsanto** [comment]
This error cannot be reproduced anymore in the latest commit 855776d .
